spring:
  application:
    name: task-manager-server
  datasource:
    url: 'jdbc:postgresql://localhost:5432/taskmanager-db'
    username: postgres
    password: datbeo09
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: 'true'
    baseline-on-migrate: 'true'
    validate-on-migrate: 'true'
    baseline-version: 1
server:
  port: '8080'